<a href="https://colab.research.google.com/github/Helyousfi/Neural-Networks/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,5],[4,5,6]], 
                         dtype = torch.float32, 
                         device = device,
                         requires_grad = True)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

# Other common initializing methods
X = torch.empty(size = (3,2))
X = torch.zeros((3,3))
X = torch.rand((3,3))
X = torch.eye(4)
X = torch.arange(start=0, end=5, step=1)
print(X)

torch.float32
cpu
torch.Size([2, 3])
True
tensor([0, 1, 2, 3, 4])


In [3]:
x = torch.tensor([2.5, 1, 1.3])
x.dtype

torch.float32

In [4]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
y.add(x)

tensor([[0.6518, 1.4489],
        [1.1882, 0.8755]])

In [5]:
y.add_(x)

tensor([[0.6518, 1.4489],
        [1.1882, 0.8755]])

In [6]:
z = torch.sub(x, y)
z

tensor([[-0.0056, -0.7851],
        [-0.8004, -0.7701]])

In [7]:
x.sub_(y)

tensor([[-0.0056, -0.7851],
        [-0.8004, -0.7701]])

In [12]:
torch.mul(x, y)

tensor([[-0.0036, -1.1375],
        [-0.9510, -0.6742]])

In [13]:
x = torch.rand(5 ,3)
x 

tensor([[0.6299, 0.3834, 0.7533],
        [0.5920, 0.7977, 0.7575],
        [0.4901, 0.8197, 0.7512],
        [0.9887, 0.4203, 0.4253],
        [0.5451, 0.7608, 0.6534]])

In [16]:
# Slicing
print(x[:,0])
print(x[2:4, :])

tensor([0.6299, 0.5920, 0.4901, 0.9887, 0.5451])
tensor([[0.4901, 0.8197, 0.7512],
        [0.9887, 0.4203, 0.4253]])


In [18]:
print(x[1, 1])
print(x[1, 1].item())

tensor(0.7977)
0.7977022528648376


In [22]:
x = torch.rand(3,4)
print(x.view(2,6))
print(x.size())
import numpy as np
np.ones((3,4)).reshape(2,6)

tensor([[0.4199, 0.2666, 0.7996, 0.1493, 0.0572, 0.6650],
        [0.9327, 0.3149, 0.0180, 0.9302, 0.9782, 0.2780]])
torch.Size([3, 4])


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
a = torch.ones(5)
a_array = a.numpy()
print(type(a_array))

<class 'numpy.ndarray'>


In [27]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [28]:
a_array

array([2., 2., 2., 2., 2.], dtype=float32)

In [37]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [36]:
a_tensor = torch.from_numpy(a)
a_tensor

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [39]:
torch.cuda.is_available()

False

In [44]:
x = torch.ones(5, 5, device=device)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [48]:
x = torch.ones(5,5)
x.to(device)
x.device

device(type='cpu')

In [49]:
x = torch.ones(5, requires_grad = True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

#### Autograd

In [52]:
x = torch.randn(3, requires_grad = True)
x   

tensor([-0.2437,  0.8027, -0.7949], requires_grad=True)

In [76]:
y = x + 2
y

tensor([1.7563, 2.8027, 1.2051], grad_fn=<AddBackward0>)

In [80]:
z = y*y
z = z.mean()
z

tensor(4.1306, grad_fn=<MeanBackward0>)

In [81]:
z.backward()
print(x.grad)


tensor([11.2804, 20.9340,  7.0762])


In [90]:
x = torch.tensor([5, 4, 3, 9], dtype=torch.float32, requires_grad=True)
x

tensor([5., 4., 3., 9.], requires_grad=True)

In [91]:
y = x * x
y

tensor([25., 16.,  9., 81.], grad_fn=<MulBackward0>)

In [93]:
z = torch.mean(y)
z.backward()

In [97]:
print(x.grad)

tensor([2.5000, 2.0000, 1.5000, 4.5000])
